-- =============================================================================
-- Greenpreneur Database Import Script — Speakers & Partners
-- Run this script in phpMyAdmin or MySQL console on your live Hostinger server.
-- =============================================================================

USE `greenpreneur`; -- Adjust database name if different on live server

-- 1. Insert Speakers & Jury
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Achal Rangaswamy', 'Business Coach & Author', 'Peers Global', '"[\"Coach\",\"Author\",\"Speaker\"]"', '/uploads/nominations/Achal Rangaswamy.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Aditya Jhunjhunwala', 'Co-Founder, ADMC & Business Coach', 'ADMC', '"[\"Coach\",\"Speaker\"]"', '/uploads/nominations/Aditya Jhunjhunwala.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Ajay Thakur', 'CEO & Managing Partner', 'TGI SME Capital Advisors LLP', '"[\"Finance\",\"Speaker\"]"', '/uploads/nominations/Ajay Thakur.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Binjan Sheth', 'Founder, Coding and More & Director', 'Thinkgreen Envirotech Pvt Ltd', '"[\"Envirotech\",\"Education\",\"Speaker\"]"', '/uploads/nominations/Binjan Sheth.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('CA Shubham Maloo', 'Chartered Accountant & Founder', 'Shubham Maloo & Co.', '"[\"Finance\",\"Consultant\",\"Speaker\"]"', '/uploads/nominations/CA Shubham Maloo.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Chandrakant Salunkhe', 'Founder & President', 'SME Chamber of India', '"[\"SME Leader\",\"President\",\"Speaker\"]"', '/uploads/nominations/Chandrakant Salunkhe.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr Parimal Merchant', 'Director, Global FMB Program', 'SP Jain School of Global Management', '"[\"Academician\",\"Director\",\"Speaker\"]"', '/uploads/nominations/Dr Parimal Merchant.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr. Krishna Singh Arya', 'SDG Champion, Mentor & Academician', 'World Leader Summit', '"[\"SDG Champion\",\"Mentor\",\"Speaker\"]"', '/uploads/nominations/Dr. Krishna Singh Arya.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Jagdish Vishwakarma', 'MoS for MSME, Cooperation & Cottage Industries', 'Government of Gujarat', '"[\"Minister\",\"MSME Leader\",\"Speaker\"]"', '/uploads/nominations/Jagdish Vishwakarma.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Kuldipsingh Kaler', 'Creative Head – Marketing', 'Tea Post', '"[\"Marketing\",\"Influencer\",\"Speaker\"]"', '/uploads/nominations/Kuldipsingh Kaler.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Madhu Menon', 'Director, Anala Outdoors & Sattva Vikas School', 'Anala Outdoors', '"[\"Biodiversity\",\"Director\",\"Speaker\"]"', '/uploads/nominations/Madhu Menon.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Moloy Chakravorty', 'Founder & Managing Director', 'Beyond Red Ocean Consulting', '"[\"Coach\",\"Consultant\",\"Speaker\"]"', '/uploads/nominations/Moloy Chakravorty.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Nayan Mehta', 'Chief Financial Officer', 'BSE (Bombay Stock Exchange) Limited', '"[\"Finance\",\"CFO\",\"Speaker\"]"', '/uploads/nominations/Nayan Mehta.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Pabiben Rabari', 'Founder', 'Pabiben.com', '"[\"Artisan\",\"Entrepreneur\",\"Speaker\"]"', '/uploads/nominations/Pabiben Rabari.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('R. Gopinath Rao', 'IEDS, Deputy Director, MSME Development Institute', 'Government of India', '"[\"Government\",\"MSME Director\",\"Speaker\"]"', '/uploads/nominations/R. Gopinath Rao.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Ramkumar Seshu', 'Business Coach, Mentor & Founder', 'Seshu Consulting', '"[\"Coach\",\"Mentor\",\"Speaker\"]"', '/uploads/nominations/Ramkumar Seshu.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Shiv Khera', 'Author, Educator & Motivational Speaker', 'Qualified Learning Systems', '"[\"Author\",\"Speaker\",\"Jury\"]"', '/uploads/nominations/Shiv Khera.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Shraddha Musale', 'Founder, FutureTayari / Actor & Presence Coach', 'FutureTayari', '"[\"Founder\",\"Actor\",\"Coach\",\"Speaker\"]"', '/uploads/nominations/Shraddha Musale.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Suresh Mansharamani', 'Founder, Tajurba Business Network & OKR Expert', 'Tajurba Business Network', '"[\"Coach\",\"Founder\",\"Speaker\",\"Jury\"]"', '/uploads/nominations/Suresh Mansharamani.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Tanvvi Rathod', 'Founder, Maisson By Tanvvi Rathod / Mentorship Expert', 'Maisson By Tanvvi Rathod', '"[\"Mentor\",\"Trainer\",\"Speaker\"]"', '/uploads/nominations/Tanvvi Rathod.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Vijay Kalantri', 'President, AIAI & Chairman', 'MVIRDC World Trade Center Mumbai', '"[\"Industry Leader\",\"President\",\"Speaker\"]"', '/uploads/nominations/Vijay  Kalantri.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Sanjay Raval', 'Author, Motivational Speaker & Entrepreneur', 'Sanjay Raval Seminars', '"[\"Author\",\"Speaker\",\"Entrepreneur\"]"', '/uploads/nominations/sanjay raval.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);

-- 2. Insert Partners
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('0 West', 'Sustainability Partner', '0 West Sustainability Solutions', '"[\"Zero Waste\",\"Sustainability\"]"', '/uploads/nominations/0 West.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('123 Eco-Solutions', 'Support Partner', '123 Group', '"[\"Eco-Solutions\",\"Green Energy\"]"', '/uploads/nominations/123.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Agroyis', 'Agro-Tech Partner', 'Agroyis Agri Solutions', '"[\"Agro-Tech\",\"Organic Farming\"]"', '/uploads/nominations/Agroyis.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('All About', 'Branding & Marketing Partner', 'All About Marketing Consultancy', '"[\"Branding\",\"Marketing\"]"', '/uploads/nominations/All About.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Body Tales', 'Organic Wellness Partner', 'The Body Tales Skin Care', '"[\"Organic Wellness\",\"Cosmetics\"]"', '/uploads/nominations/Body Tales.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Concepts Green', 'Green Consultancy Partner', 'Concepts Green Consultancy', '"[\"Green Tech\",\"Consulting\"]"', '/uploads/nominations/Concepts. green.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('DevX', 'Ecosystem & Incubation Partner', 'DevX Co-Working & Innovation', '"[\"Incubation\",\"Startups\",\"Co-working\"]"', '/uploads/nominations/DevX.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Glam Greens Herbal Care', 'Natural Wellness Partner', 'Glam Greens Herbal Care Products', '"[\"Herbal Care\",\"Organic Products\"]"', '/uploads/nominations/Glam Greens Herbal Care.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Gyan Enviro', 'Environmental Consultant Partner', 'Gyan Enviro Consultants', '"[\"Waste Management\",\"Audit\",\"Environmental\"]"', '/uploads/nominations/Gyan Enviro.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('IBS', 'Education & Knowledge Partner', 'ICFAI Business School', '"[\"Education\",\"Mentorship\",\"Business School\"]"', '/uploads/nominations/IBS.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('IDBI Bank', 'Banking Partner', 'IDBI Bank Limited', '"[\"Banking\",\"Finance\",\"SME Loans\"]"', '/uploads/nominations/IDBI Bank.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Navitas Green Solutions Pvt. Ltd.', 'Solar Technology Partner', 'Navitas Solar', '"[\"Solar Energy\",\"Renewables\",\"Manufacturing\"]"', '/uploads/nominations/Navitas Green Solutions Pvt. Ltd.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Rupee Boss', 'Financial Services Partner', 'Rupeeboss Financial Services Pvt. Ltd.', '"[\"Financial Services\",\"Loans\",\"SME Growth\"]"', '/uploads/nominations/Rupee Boss.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('WAACAB', 'Solar Energy Solutions Partner', 'WAACAB Solar Technology', '"[\"Solar Tech\",\"Renewables\"]"', '/uploads/nominations/WAACAB.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
